### ISSUE TITLE
LLVM 13

### ISSUE THREAD

**Issue by SamuelMarks** [banach-space/clang-tutor#20]
FYI: https://releases.llvm.org/13.0.0/docs/ReleaseNotes.html

EDIT: I saw your 535a0f9c2c0aca776455d771b6b42594b6c93b4c… need a hand porting to LLVM@13?

**Comment by banach-space** [comment]
Hi, thanks for visiting! 👋🏻 

> need a hand porting to LLVM@13?

Yes, please! Do you have the bandwidth? I've almost finished porting **llvm-tutor**, but have not started here yet.

-Andrzej

**Comment by SamuelMarks** [comment]
I'll give it a shot. My PR will be a WiP, but let's see how far I can get. Using this [upgrade process] as a way to learn the toolchain and LLVM libraries.

**Comment by banach-space** [comment]
Massive thanks for all the help!
